### ISSUE TITLE
Print and Export Song List is not working

### ISSUE THREAD

**Issue by garymangilog** [AwayJob/WOW-Fiesta-Song-Loader#1]
Hi, Can you please help why can't I click the Print and Export Song list?

**Comment by AwayJob** [comment]
I recommend this:

## 1. Add your USB Device
- Any device, it doesn't to be your pre-included USB.

## 2. Click `Cloud Midi`.
- And this should pop up:
![image](https://github.com/AwayJob/WOW-Fiesta-Song-Loader/assets/66241829/bef05eaf-68f0-4124-82f5-de76b3316a6d)

## 3. After downloading, go to your USB in File Explorer.
- There should be a `midisongsbook.pdf` (You can print this). That's all of the midi songs from the WOW! Fiesta's Song Loader.
![image](https://github.com/AwayJob/WOW-Fiesta-Song-Loader/assets/66241829/0a589ac5-84d4-4aa7-8f7a-869d4198851a)
- **Note:** Your factory built-in songs is DIFFERENT from the WOW! Fiesta's Song Loader.

## 4. So to actually use the songs, eject the USB from the computer, then plug it to your machine. Finally, turn it on.
- **Note:** If you plug your USB whilst the machine is on, the machine will not detect the new songs.

## 5. Use the new pdf/printed songbook to pick the new songs.
- **Note:** Again, your existing songbook is different to the new songbook.

**Comment by garymangilog** [comment]
Oh thank you so much that works really appreciate your fast response. Have a Safe and Happy New Year.
